
#The LABEL instruction is used to add metadata to a Docker image. 
#It helps store information like the author, version, description, or any custom key-value pair.

FROM almalinux:9
LABEL author="Srinivasak" \
      company="joindevops" \
      topic="dockerfiles" \
      duration="2 hours"
