
# The ENTRYPOINT instruction defines the main command that will always run when a container starts. 
# Unlike CMD, ENTRYPOINT is not overridden by arguments passed during docker run.
FROM almalinux:9
CMD ["ping","google.com"]
