
#The RUN instruction in a Dockerfile is used to execute commands during the image build process. 
#It allows you to install software, update packages, or configure the system inside the image.

FROM almalinux:9
RUN dnf install nginx -y