
#The ENV instruction in a Dockerfile is used to define environment variables inside the container. 
#These variables can be used in subsequent Dockerfile instructions and accessed by applications running inside the container.


FROM almalinux:9
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120hrs"